version: 2

sources:
    - name: staging
        database: datatalks-de-zoomcamp
        schema: tripdata_all

        tables:
            - name: green_tripdata
            - name: yellow_tripdata